/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidemo_NdkUtils_NdkUtilsStatic */

#ifndef _Included_com_example_jnidemo_NdkUtils_NdkUtilsStatic
#define _Included_com_example_jnidemo_NdkUtils_NdkUtilsStatic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnidemo_NdkUtils_NdkUtilsStatic
 * Method:    getTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidemo_NdkUtils_NdkUtilsStatic_getTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
